language: objective-c
osx_image: xcode11.3

script:
    - xcodebuild clean build test -project FAQView.xcodeproj -scheme FAQView -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
